"""
Professional PDF report generator using ReportLab Platypus.

Produces a multi-page client-ready document:

    Page 1     — COVER PAGE
                  Project name · Client · Date · Company · (optional logo)
    Page 2     — PROJECT DETAILS
                  Element type, dimensions, cover, bar details
    Page 3+    — BBS TABLE
                  Paginates if long. Bar mark / Element / Description / Dia /
                  Cut Len / Qty / Total Len / Weight
    Page 4+    — BAR DRAWINGS
                  One drawing per bar mark with dimensions & shape labels
    Final page — STEEL ORDER SUMMARY
                  Dia-wise grouping, totals, 5% wastage, 12 m rod count

Every page carries:
    - Header  : company name + report title
    - Footer  : page number + "Generated by BBS System"
    - Watermark: "FOR CONSTRUCTION USE" diagonal, faint grey
"""

from datetime import datetime
import os
from typing import Dict, Any, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import (BaseDocTemplate, PageTemplate, Frame,
                                Paragraph, Spacer, Table, TableStyle,
                                PageBreak, Image, KeepTogether)
from reportlab.platypus.flowables import HRFlowable

from services.bar_drawings import make_drawing_for_row


# ---------------- Theme ----------------

PRIMARY    = colors.HexColor("#1F4E78")
PRIMARY_2  = colors.HexColor("#2E7CB6")
TEXT       = colors.HexColor("#1F2937")
MUTED      = colors.HexColor("#6B7280")
ROW_ALT    = colors.HexColor("#EAF1F8")
SUCCESS    = colors.HexColor("#2E7D32")
DANGER     = colors.HexColor("#C62828")

PAGE_W, PAGE_H = A4
MARGIN_L = 18 * mm
MARGIN_R = 18 * mm
MARGIN_T = 22 * mm
MARGIN_B = 22 * mm

WATERMARK_TEXT = "FOR CONSTRUCTION USE"
COMPANY_DEFAULT = "BBS Automation"
GENERATED_BY    = "Generated by BBS System"


# ---------------- Page decoration callback ----------------

def _draw_page_decorations(canv: Canvas, doc):
    """Draw watermark, header & footer on EVERY page (called by ReportLab)."""
    canv.saveState()

    project_name = getattr(doc, "_project_name", "Bar Bending Schedule")
    company_name = getattr(doc, "_company_name", COMPANY_DEFAULT)
    page_num = canv.getPageNumber()

    # --------- Watermark (very faint, diagonal) ---------
    canv.saveState()
    canv.translate(PAGE_W / 2, PAGE_H / 2)
    canv.rotate(45)
    canv.setFont("Helvetica-Bold", 60)
    canv.setFillColor(colors.HexColor("#1F4E78"))
    canv.setFillAlpha(0.06)
    canv.drawCentredString(0, 0, WATERMARK_TEXT)
    canv.restoreState()

    # --------- Header ---------
    canv.setStrokeColor(PRIMARY)
    canv.setLineWidth(0.5)
    canv.line(MARGIN_L, PAGE_H - 14 * mm, PAGE_W - MARGIN_R, PAGE_H - 14 * mm)

    canv.setFont("Helvetica-Bold", 9)
    canv.setFillColor(PRIMARY)
    canv.drawString(MARGIN_L, PAGE_H - 11 * mm, company_name)

    canv.setFont("Helvetica", 9)
    canv.setFillColor(MUTED)
    canv.drawRightString(PAGE_W - MARGIN_R, PAGE_H - 11 * mm,
                         project_name)

    # --------- Footer ---------
    canv.setStrokeColor(MUTED)
    canv.setLineWidth(0.3)
    canv.line(MARGIN_L, 14 * mm, PAGE_W - MARGIN_R, 14 * mm)

    canv.setFont("Helvetica", 8)
    canv.setFillColor(MUTED)
    canv.drawString(MARGIN_L, 9 * mm, GENERATED_BY)
    canv.drawCentredString(PAGE_W / 2, 9 * mm,
                           f"IS 456:2000 · IS 2502:1963 compliant")
    canv.drawRightString(PAGE_W - MARGIN_R, 9 * mm, f"Page {page_num}")

    canv.restoreState()


# ---------------- Styles ----------------

def _styles():
    base = getSampleStyleSheet()
    return {
        "h1":       ParagraphStyle("h1", parent=base["Heading1"],
                                   fontSize=22, textColor=PRIMARY,
                                   spaceAfter=6, leading=26),
        "h2":       ParagraphStyle("h2", parent=base["Heading2"],
                                   fontSize=14, textColor=PRIMARY,
                                   spaceBefore=10, spaceAfter=8, leading=18),
        "h3":       ParagraphStyle("h3", parent=base["Heading3"],
                                   fontSize=11, textColor=PRIMARY,
                                   spaceBefore=6, spaceAfter=4),
        "body":     ParagraphStyle("body", parent=base["BodyText"],
                                   fontSize=10, textColor=TEXT,
                                   leading=14),
        "small":    ParagraphStyle("small", parent=base["BodyText"],
                                   fontSize=8, textColor=MUTED, leading=11),
        "cover_t":  ParagraphStyle("cover_t", parent=base["Heading1"],
                                   fontSize=32, textColor=PRIMARY,
                                   alignment=TA_CENTER, leading=38),
        "cover_s":  ParagraphStyle("cover_s", parent=base["Heading2"],
                                   fontSize=14, textColor=MUTED,
                                   alignment=TA_CENTER, leading=18,
                                   spaceAfter=20),
        "cover_l":  ParagraphStyle("cover_l", parent=base["BodyText"],
                                   fontSize=11, textColor=TEXT,
                                   alignment=TA_CENTER, leading=15),
        "stamp_ok": ParagraphStyle("stamp_ok", parent=base["BodyText"],
                                   fontSize=10, textColor=SUCCESS),
        "stamp_no": ParagraphStyle("stamp_no", parent=base["BodyText"],
                                   fontSize=10, textColor=DANGER),
        "discl":    ParagraphStyle("discl", parent=base["BodyText"],
                                   fontSize=9, textColor=DANGER,
                                   alignment=TA_CENTER, leading=12,
                                   borderPadding=8,
                                   borderWidth=1,
                                   borderColor=DANGER,
                                   borderRadius=4),
    }


# ---------------- Table builder ----------------

def _styled_table(data, col_widths=None):
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING",(0, 0), (-1, 0), 7),
        ("TOPPADDING",   (0, 0), (-1, 0), 7),
        ("ALIGN",        (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("FONTSIZE",     (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
            [colors.whitesmoke, ROW_ALT]),
        ("GRID",         (0, 0), (-1, -1), 0.4, colors.HexColor("#94A3B8")),
        ("LEFTPADDING",  (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


# ---------------- Page sections ----------------

def _cover_page(meta: Dict[str, Any], st) -> list:
    """Page 1 — Cover."""
    fl = []
    fl.append(Spacer(1, 60 * mm))
    fl.append(Paragraph("Bar Bending Schedule", st["cover_t"]))
    fl.append(Paragraph("Reinforcement Detail Report", st["cover_s"]))
    fl.append(Spacer(1, 18 * mm))

    # Optional logo
    logo_path = meta.get("logo_path")
    if logo_path and os.path.isfile(logo_path):
        try:
            img = Image(logo_path, width=40 * mm, height=40 * mm,
                        kind="proportional")
            img.hAlign = "CENTER"
            fl.append(img)
            fl.append(Spacer(1, 12 * mm))
        except Exception:
            pass

    # Project info card
    info_rows = [
        ["Project",  meta.get("project_name") or "—"],
        ["Client",   meta.get("client_name")  or "—"],
        ["Element",  meta.get("element_type", "").title() or "—"],
        ["Date",     datetime.now().strftime("%d %b %Y")],
        ["Prepared by", meta.get("company_name") or COMPANY_DEFAULT],
    ]
    t = Table(info_rows, colWidths=[40 * mm, 90 * mm])
    t.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 11),
        ("TEXTCOLOR",   (0, 0), (0, -1), MUTED),
        ("TEXTCOLOR",   (1, 0), (1, -1), TEXT),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("LINEBELOW",   (0, 0), (-1, -2), 0.4, colors.HexColor("#E5E7EB")),
    ]))
    t.hAlign = "CENTER"
    fl.append(t)

    fl.append(Spacer(1, 30 * mm))
    fl.append(Paragraph(
        "<b>For Construction Use</b><br/>"
        "<i>Final check by qualified structural engineer required "
        "before fabrication.</i>",
        st["discl"]))

    fl.append(PageBreak())
    return fl


def _project_details_page(result: Dict[str, Any], st) -> list:
    """Page 2 — Input parameters echo, element-aware."""
    fl = []
    inp = result["input_echo"]
    et = inp.get("element_type", "").lower()

    fl.append(Paragraph("Project Details", st["h1"]))
    fl.append(HRFlowable(width="100%", thickness=1, color=PRIMARY,
                         spaceAfter=10))

    fl.append(Paragraph("1. Element &amp; Dimensions", st["h2"]))

    if et == "slab":
        items = [
            ("Element Type",       "Slab"),
            ("Shorter Span",       f"{inp.get('short_span', inp.get('width', '—'))} mm"),
            ("Longer Span",        f"{inp.get('long_span', inp.get('length', '—'))} mm"),
            ("Clear Cover",        f"{inp.get('cover', '—')} mm"),
        ]
    elif et == "column":
        items = [
            ("Element Type",       "Column"),
            ("Width × Depth",      f"{inp.get('width', '—')} × {inp.get('depth', '—')} mm"),
            ("Storey Height",      f"{inp.get('length', '—')} mm"),
            ("Clear Cover",        f"{inp.get('cover', '—')} mm"),
        ]
    else:  # beam
        items = [
            ("Element Type",       "Beam"),
            ("Width × Depth",      f"{inp.get('width', '—')} × {inp.get('depth', '—')} mm"),
            ("Span / Length",      f"{inp.get('length', '—')} mm"),
            ("Clear Cover",        f"{inp.get('cover', '—')} mm"),
        ]
    fl.append(_two_col_info_table(items))
    fl.append(Spacer(1, 6))

    fl.append(Paragraph("2. Reinforcement Details", st["h2"]))

    if et == "slab":
        ri = [
            ("Main Bar Dia",       f"{inp.get('main_bar_dia', '—')} mm"),
            ("Main Bar Spacing",   f"{inp.get('main_bar_spacing', inp.get('stirrup_spacing', '—'))} mm"),
            ("Distribution Bar Dia",     f"{inp.get('dist_bar_dia', inp.get('stirrup_dia', '—'))} mm"),
            ("Distribution Bar Spacing", f"{inp.get('dist_bar_spacing', inp.get('stirrup_spacing', '—'))} mm"),
            ("Hook Type",          f"{inp.get('hook_type', '—')}°"),
            ("Lap Length",         f"{inp.get('lap_length', 0) or 0} mm"),
        ]
    elif et == "column":
        ri = [
            ("Main Bar Dia",       f"{inp.get('main_bar_dia', '—')} mm"),
            ("Main Bar Quantity",  f"{inp.get('main_bar_qty', '—')} nos."),
            ("Lateral Tie Dia",    f"{inp.get('stirrup_dia', '—')} mm"),
            ("Tie Spacing",        f"{inp.get('stirrup_spacing', '—')} mm"),
            ("Hook Type",          f"{inp.get('hook_type', '—')}°"),
            ("Lap Length",         f"{inp.get('lap_length', 0) or 0} mm"),
        ]
    else:  # beam
        ri = [
            ("Main Bar Dia",       f"{inp.get('main_bar_dia', '—')} mm"),
            ("Main Bar Quantity",  f"{inp.get('main_bar_qty', '—')} nos."),
            ("Stirrup Dia",        f"{inp.get('stirrup_dia', '—')} mm"),
            ("Stirrup Spacing",    f"{inp.get('stirrup_spacing', '—')} mm"),
            ("Hook Type",          f"{inp.get('hook_type', '—')}°"),
            ("Lap Length",         f"{inp.get('lap_length', 0) or 0} mm"),
        ]
    fl.append(_two_col_info_table(ri))

    fl.append(Spacer(1, 8))
    fl.append(Paragraph("3. Calculation Settings", st["h2"]))
    cs = [
        ("Quantity Mode",  inp.get("qty_mode", "standard").title()),
        ("Standards",      "IS 456:2000, IS 2502:1963"),
        ("Wastage Factor", "5% (industry default)"),
        ("Standard Rod",   "12 m"),
    ]
    fl.append(_two_col_info_table(cs))

    fl.append(PageBreak())
    return fl


def _two_col_info_table(items):
    """Render a (label, value) list as a clean 4-column (lbl,val,lbl,val) table."""
    rows = [["Parameter", "Value", "Parameter", "Value"]]
    for i in range(0, len(items), 2):
        left = items[i]
        right = items[i + 1] if i + 1 < len(items) else ("", "")
        rows.append([left[0], str(left[1]), right[0], str(right[1])])
    return _styled_table(rows, col_widths=[42*mm, 42*mm, 42*mm, 42*mm])


def _bbs_table_page(result: Dict[str, Any], st) -> list:
    """BBS table page (auto-paginates if long)."""
    fl = []
    fl.append(Paragraph("Bar Bending Schedule (BBS)", st["h1"]))
    fl.append(HRFlowable(width="100%", thickness=1, color=PRIMARY,
                         spaceAfter=10))
    fl.append(Paragraph(
        f"Element: <b>{result['summary']['element_type'].title()}</b> &nbsp;|&nbsp; "
        f"Total bars: {result['summary']['total_bars']} &nbsp;|&nbsp; "
        f"Net weight: {result['summary']['total_weight_kg_net']} kg",
        st["body"]))
    fl.append(Spacer(1, 8))

    # Build the table
    headers = ["Bar Mark", "Element", "Description", "Dia\n(mm)",
               "Cutting Len\n(mm)", "Qty", "Total Len\n(m)", "Weight\n(kg)"]
    rows = [headers]
    for r in result["bbs"]:
        rows.append([
            r["bar_mark"], r.get("element_type", "-").title(),
            r["description"],
            r["dia_mm"], r["cutting_length_mm"], r["quantity"],
            r["total_length_m"], r["total_weight_kg"],
        ])
    rows.append([
        "TOTAL", "", "", "", "", "",
        result["summary"]["total_length_m"],
        result["summary"]["total_weight_kg_net"]
    ])
    fl.append(_styled_table(rows,
        col_widths=[18*mm, 18*mm, 50*mm, 16*mm, 22*mm, 14*mm, 22*mm, 22*mm]))

    # Verification stamp
    if "verification" in result:
        v = result["verification"]
        fl.append(Spacer(1, 10))
        if v["passed"]:
            fl.append(Paragraph(
                f"<b>✓ Engineering Verified</b> — {v.get('method', 'double-check passed')}.",
                st["stamp_ok"]))
        else:
            fl.append(Paragraph(
                "<b>✗ Verification FAILED</b> — issues: "
                + "; ".join(v.get("issues", [])),
                st["stamp_no"]))

    fl.append(PageBreak())
    return fl


def _drawings_page(result: Dict[str, Any], st) -> list:
    """One drawing per bar mark — vector graphics, sharp at any zoom."""
    fl = []
    fl.append(Paragraph("Bar Shape Drawings", st["h1"]))
    fl.append(HRFlowable(width="100%", thickness=1, color=PRIMARY,
                         spaceAfter=10))
    fl.append(Paragraph(
        "Schematic drawings of every bar in the schedule. "
        "Numbers next to each shape are exact mm dimensions. "
        "<i>Drawings are not to scale.</i>", st["small"]))
    fl.append(Spacer(1, 6))

    inp = result["input_echo"]
    avail_w = PAGE_W - MARGIN_L - MARGIN_R   # ~174 mm

    for r in result["bbs"]:
        # Each drawing card: title strip + drawing + spec strip
        canvas_w = avail_w - 12  # leave a touch of padding
        canvas_h = 80 * mm if r.get("shape", "").lower().startswith("rect") \
                   else 55 * mm
        drawing = make_drawing_for_row(r, inp, canvas_w, canvas_h)

        # Wrap drawing inside a bordered box (so it looks like a card)
        title = f"<b>{r['bar_mark']} — {r['description']}</b>"
        info  = (f"Dia: <b>{r['dia_mm']} mm</b> &nbsp; · &nbsp; "
                 f"Cutting length: <b>{r['cutting_length_mm']} mm</b> &nbsp; · &nbsp; "
                 f"Quantity: <b>{r['quantity']}</b> &nbsp; · &nbsp; "
                 f"Weight: <b>{r['total_weight_kg']} kg</b>")
        card = [
            Paragraph(title, st["h3"]),
            drawing,
            Paragraph(info, st["small"]),
            Spacer(1, 6),
        ]
        fl.append(KeepTogether(card))

    fl.append(PageBreak())
    return fl


def _final_order_page(result: Dict[str, Any], st) -> list:
    """Steel order summary."""
    fl = []
    fl.append(Paragraph("Final Steel Order Summary", st["h1"]))
    fl.append(HRFlowable(width="100%", thickness=1, color=PRIMARY,
                         spaceAfter=10))
    fl.append(Paragraph(
        "Diameter-wise grouping with 5% wastage applied. "
        "Standard rod length = 12 m. "
        "Hand this directly to your supplier.", st["body"]))
    fl.append(Spacer(1, 8))

    headers = ["Diameter\n(mm)", "Net Length\n(m)", "Net Weight\n(kg)",
               "Wastage\n%", "Order Length\n(m)", "Order Weight\n(kg)",
               "12 m Rods"]
    rows = [headers]
    for r in result["final_order"]:
        rows.append([
            r["dia_mm"], r["net_length_m"], r["net_weight_kg"],
            f'{r["wastage_pct"]}%', r["order_length_m"],
            r["order_weight_kg"], r["rods_12m_required"],
        ])
    rows.append([
        "GRAND TOTAL", "", "", "",
        result["summary"]["total_order_length_m"],
        result["summary"]["total_weight_kg_with_wastage"], ""
    ])
    fl.append(_styled_table(rows,
        col_widths=[24*mm, 24*mm, 24*mm, 18*mm, 26*mm, 26*mm, 22*mm]))

    # Big summary card
    fl.append(Spacer(1, 14))
    summary_rows = [
        ["Total Bars",                 str(result["summary"]["total_bars"])],
        ["Net Weight (no wastage)",    f"{result['summary']['total_weight_kg_net']} kg"],
        ["Order Weight (with 5%)",     f"{result['summary']['total_weight_kg_with_wastage']} kg"],
        ["Total Order Length",         f"{result['summary']['total_order_length_m']} m"],
    ]
    s = Table(summary_rows, colWidths=[80*mm, 50*mm])
    s.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, -1), ROW_ALT),
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 11),
        ("TEXTCOLOR",   (0, 0), (0, -1), TEXT),
        ("TEXTCOLOR",   (1, 0), (1, -1), PRIMARY),
        ("FONTNAME",    (1, 0), (1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOX",         (0, 0), (-1, -1), 0.6, PRIMARY),
        ("LINEBELOW",   (0, 0), (-1, -2), 0.3, colors.HexColor("#CBD5E1")),
    ]))
    s.hAlign = "CENTER"
    fl.append(s)

    # Disclaimer
    fl.append(Spacer(1, 18))
    fl.append(Paragraph(
        "<b>Disclaimer.</b> This bar bending schedule is auto-generated based "
        "on the inputs provided. Final dimensions, lap lengths, and detailing "
        "must be verified against site drawings and reviewed by a qualified "
        "structural engineer before steel fabrication. The issuing party "
        "accepts no responsibility for errors arising from incorrect input "
        "data or unverified use on site.",
        st["small"]))

    return fl


# ---------------- Public API ----------------

def generate_pdf(result: Dict[str, Any], out_dir: str,
                 project_name: str = "BBS_Report",
                 client_name: Optional[str] = None,
                 company_name: Optional[str] = None,
                 logo_path: Optional[str] = None) -> str:
    """
    Generate a multi-page professional PDF report and return its absolute path.

    Args:
        result        : output of `build_bbs(payload)`
        out_dir       : directory to save into (created if absent)
        project_name  : appears in header on every page + cover page
        client_name   : appears on cover page
        company_name  : appears on cover + every page header
        logo_path     : absolute path to a .png/.jpg logo (optional, cover only)
    """
    os.makedirs(out_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_proj = "".join(c for c in (project_name or "BBS_Report")
                        if c.isalnum() or c in "_-") or "BBS_Report"
    filename = f"{safe_proj}_{timestamp}.pdf"
    path = os.path.join(out_dir, filename)

    # Build doc
    doc = BaseDocTemplate(
        path, pagesize=A4,
        leftMargin=MARGIN_L, rightMargin=MARGIN_R,
        topMargin=MARGIN_T, bottomMargin=MARGIN_B,
        title=project_name or "BBS Report",
        author=company_name or COMPANY_DEFAULT,
    )

    # Stash metadata on the doc so the page-callback can read it
    doc._project_name = project_name or "Bar Bending Schedule"
    doc._company_name = company_name or COMPANY_DEFAULT

    # Single frame, A4
    frame = Frame(MARGIN_L, MARGIN_B,
                  PAGE_W - MARGIN_L - MARGIN_R,
                  PAGE_H - MARGIN_T - MARGIN_B,
                  id="main", showBoundary=0)
    template = PageTemplate(id="main", frames=[frame],
                            onPage=_draw_page_decorations)
    doc.addPageTemplates([template])

    # Compose flowables
    st = _styles()
    meta = {
        "project_name": project_name,
        "client_name":  client_name,
        "company_name": company_name or COMPANY_DEFAULT,
        "element_type": result["summary"]["element_type"],
        "logo_path":    logo_path,
    }

    flowables = []
    flowables += _cover_page(meta, st)
    flowables += _project_details_page(result, st)
    flowables += _bbs_table_page(result, st)
    flowables += _drawings_page(result, st)
    flowables += _final_order_page(result, st)

    doc.build(flowables)
    return path
